"""Added time_expires to user

Revision ID: 699eaaf679d2
Revises: 164eea7df201
Create Date: 2023-01-21 11:00:29.033590

"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy_multi_tenant.core.db.migrations import for_each_tenant_schema

# revision identifiers, used by Alembic.
# pylint: disable=invalid-name
revision = '699eaaf679d2'
down_revision = '164eea7df201'
branch_labels = None
depends_on = None
# pylint: enable=invalid-name


@for_each_tenant_schema
def upgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # use schema_quoted in queries like op.execute(f"DROP TYPE {schema_quoted}.myenum")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_expires', sa.DateTime(timezone=True), nullable=True), schema='tenant_default')
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_expires', schema='tenant_default')
    # ### end Alembic commands ###
