"""Added password column

Revision ID: bff9d3c48506
Revises: 2f372e99f219
Create Date: 2022-12-22 18:16:04.629770

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bff9d3c48506"
down_revision = "2f372e99f219"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
